config/routes.rb
Rails.application.routes.draw do
  #statics
  get '/' => "pages#home"
  #devise
  devise_for :users, :controllers => { :omniauth_callbacks => "callbacks" }
  #resources
  resources :ingredients
  #Sandwiches
  resources :sandwiches, except: [:show] do
    scope module: 'sandwiches' do 
      resources :comments
    end
  end
  get '/sandwiches/keywords' => "sandwiches#keywords"
  get '/sandwiches/search' => "sandwiches#search"
  #instagram callbacks
  get '/challenge_callback' => "sandwiches#instagram_challenge"
  post '/challenge_callback' => "sandwiches#new_sandwich_from_instagram"

  namespace :sandwiches do
    get '/:id/like' => 'likes#like' 
  end
end

app/models/sandwich.rb
class Sandwich < ActiveRecord::Base
	has_attached_file :sandwich_image, :styles => { :medium => "300x300>", :thumb => "100x100>" }
    has_and_belongs_to_many :ingredients
    has_many :comments
    
    searchkick

    validates :description, uniqueness: true
    validates_attachment_content_type :sandwich_image, :content_type => /\Aimage\/.*\Z/

    paginates_per 20
    
    default_scope { order("created_at DESC") }

    def sandwich_image_url
    	self.sandwich_image.url(:medium)
    end

end

app/controllers/sandwiches/comments_controller.rb
class Sandwiches::CommentsController < ApplicationController
	before_action :set_sandwich

	def index
		@comments = @sandwich.comments.order("created_at DESC")
		if !@sandwich
			render status: 404,  json: "Sandwich not found"
		else
			render status: 200, json: @comments.to_json(:include => :author)
		end
	end

	def create
		comment = @sandwich.comments.new(comment: params[:text], author_id: current_user.id)

		if comment.save
			render status: 200, json: @sandwich.comments.order("created_at DESC").to_json(:include => :author)
		else
			render status: 400, json: "Comment not added"
		end
	end

	private

	def set_sandwich
		@sandwich = Sandwich.find_by_id(params[:sandwich_id])
	end
end

app/controllers/sandwiches/likes_controller.rb
class Sandwiches::LikesController < ApplicationController
	def like
		render json: "Hey"
	end

	def unlike
	end
end

app/controllers/sandwiches_controller.rb
require 'keyword_finder'

class SandwichesController < ApplicationController
  before_action      :set_sandwich, only: [:edit, :update, :destroy]
  skip_before_action :verify_authenticity_token
  include Keywords

  def instagram_challenge
    render json: params["hub.challenge"]
  end

  def new_sandwich_from_instagram
    user = User.first
    # last_sandwich = Sandwich.last.ig_id.to_s[0..18] 
    InstagramSandwichJob.perform_later(user.token)
    render :nothing => true
  end
  
  def index
      @sandwiches = Sandwich.all.page(params[:page])
      @meta = meta_for(@sandwiches)
      render json: {
                    sandwiches: @sandwiches.as_json(:methods => :sandwich_image_url),
                    meta: @meta
                   }
  end

  def keywords
      sandwiches =  $redis.get("sandwich_keywords")
      $redis.del("sandwich_keywords")

      if sandwiches.nil?
        sandwiches = Keywords.find_keywords(Sandwich).to_json
        $redis.set("sandwich_keywords", sandwiches)
        $redis.expire("sandwich_keywords", 1.hour.to_i)
      end
      @keywords = JSON.load sandwiches
      render json: @keywords
  end

  def search
    @sandwiches = Sandwich.search(
        params[:term], 
        page: params[:page], 
        per_page: 20)
    @meta = meta_for(@sandwiches)
  end

  def new
    @sandwich = Sandwich.new
  end

  def edit
  end

  def create
    @sandwich = Sandwich.new(sandwich_params)

    respond_to do |format|
      if @sandwich.save
        format.html { redirect_to @sandwich, notice: 'Sandwich was successfully created.' }
        format.json { render :show, status: :created, location: @sandwich }
      else
        format.html { render :new }
        format.json { render json: @sandwich.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @sandwich.update(sandwich_params)
        format.html { redirect_to @sandwich, notice: 'Sandwich was successfully updated.' }
        format.json { render :show, status: :ok, location: @sandwich }
      else
        format.html { render :edit }
        format.json { render json: @sandwich.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @sandwich.destroy
    respond_to do |format|
      format.html { redirect_to sandwiches_url, notice: 'Sandwich was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

    def redis_key_search_sandwiches(term, page)
      "sandwiches_#{term}_#{page}_sandwiches"
    end

    def redis_key_search_meta(term, page)
      "sandwiches_#{term}_#{page}_meta"
    end

    def expire_keys(keys, expiration_time)
      keys.each do | key |
        $redis.expire(key, expiration_time)
      end
    end

    def meta_for(sandwiches)
      return {
        current_page: sandwiches.current_page,
        next_page: sandwiches.next_page,
        prev_page: sandwiches.prev_page,
        total_pages: sandwiches.total_pages,
        total_count: sandwiches.total_count
      }
    end

    def set_sandwich
      @sandwich = Sandwich.find(params[:id])
    end

    def sandwich_params
      params.require(:sandwich).permit(:name, :description, :sandwich_image)
    end
end

app/helpers/sandwiches/likes_helper.rb
module Sandwiches::LikesHelper
end

app/helpers/sandwiches_helper.rb
module SandwichesHelper
end

app/views/sandwiches/_form.html.erb
<%= form_for @sandwich, :html => { :multipart => true } do |f| %>
  <% if @sandwich.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@sandwich.errors.count, "error") %> prohibited this sandwich from being saved:</h2>

      <ul>
      <% @sandwich.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
     <%= f.label :sandwich_image %><br>
     <%= f.file_field :sandwich_image %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/sandwiches/edit.html.erb
<h1>Editing Sandwich</h1>

<%= render 'form' %>

<%= link_to 'Show', @sandwich %> |
<%= link_to 'Back', sandwiches_path %>

app/views/sandwiches/index.html.erb
<p id="notice"><%= notice %></p>
<%= form_tag("/index", method: "get") do  %>
 <%= select_tag(:sandwich_id, options_from_collection_for_select(Sandwich.all, :id, :description)) %>
 <%= submit_tag("Search") %>
<% end %>
<h1>Listing Sandwiches</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @sandwiches.each do |sandwich| %>
      <tr>
        <td><%= sandwich.name %></td>
        <td><%= sandwich.description %></td>
        <td><%= image_tag(sandwich.sandwich_image, class: "sandwich-image ") %>
        <td><%= link_to 'Show', sandwich %></td>
        <td><%= link_to 'Edit', edit_sandwich_path(sandwich) %></td>
        <td><%= link_to 'Destroy', sandwich, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Sandwich', new_sandwich_path %>

app/views/sandwiches/new.html.erb
<h1>New Sandwich</h1>

<%= render 'form' %>

<%= link_to 'Back', sandwiches_path %>

app/views/sandwiches/sandwichswiper.html.erb
<div class="container-fluid">
<nav class="navbar navbar-default col-sm-6 text-center" role="navigation">
  <!-- Brand and toggle get grouped for better mobile display -->
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <a class="navbar-brand" href="#">Brand</a>
    <%= link_to('Logout', destroy_user_session_path, method: 'delete', class: "navbar-brand") %>
  </div>
  <!-- Collect the nav links, forms, and other content for toggling -->
  <div class="collapse navbar-collapse navbar-ex1-collapse">
    <ul class="nav navbar-nav">
      <li class="active"><a class="navbar-heading" href="#">Top Restaurants</a></li>
      <li><a href="#">Link</a></li>
      <li><a href="#">Link</a></li>
      <li><a href="#">Link</a></li>
      <li><a href="#">Link</a></li>
      <li><a href="#">Link</a></li>
    </ul>
    <ul class="nav navbar-nav navbar-right">
      <li><a class="navbar-heading" href="#">Link</a></li>
      <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Dropdown <b class="caret"></b></a>
        <ul class="dropdown-menu">
          <li><a href="#">Action</a></li>
          <li><a href="#">Another action</a></li>
          <li><a href="#">Something else here</a></li>
          <li><a href="#">Separated link</a></li>
        </ul>
      </li>
    </ul>
  </div><!-- /.navbar-collapse -->
</nav>

  <!-- <div class="sandwich-wrapper col-sm-8"> -->
    <%= react_component 'SandwichSlider' %>
  <!-- </div> -->
</div>

app/views/sandwiches/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @sandwich.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @sandwich.description %>
</p>

<%= link_to 'Edit', edit_sandwich_path(@sandwich) %> |
<%= link_to 'Back', sandwiches_path %>